### ISSUE TITLE
非常好奇ShellClash能不能安装

### ISSUE THREAD

**Issue by Zippowxk** [z-jack/BE5000_GetShell#1]
RT

**Comment by z-jack** [comment]
我感觉只要交叉编译一下就能行 不过不确定板载内存啥的够不够

**Comment by moyuwuhen601** [comment]
可以安装，我成功安装了，不过存储不太够，而且也不要对网速有太大的期望

**Comment by mwnu** [comment]
> 可以安装，我成功安装了，不过存储不太够，而且也不要对网速有太大的期望

查了一下128MB闪存，和经典型号ax6000以及ax6s一样，确实不太够。

**Comment by moyuwuhen601** [comment]
> > 可以安装，我成功安装了，不过存储不太够，而且也不要对网速有太大的期望
> 
> 
> 
> 查了一下128MB闪存，和经典型号ax6000以及ax6s一样，确实不太够。

安装是一点问题没有的，可以装到内存中，只是速度实在是感人，我用着也就40mbps左右

**Comment by mwnu** [comment]
> > > 可以安装，我成功安装了，不过存储不太够，而且也不要对网速有太大的期望
> > 
> > 
> > 查了一下128MB闪存，和经典型号ax6000以及ax6s一样，确实不太够。
> 
> 安装是一点问题没有的，可以装到内存中，只是速度实在是感人，我用着也就40mbps左右

小内存+小闪存的路由器过段时间就要换，我已经折腾几回了，也许应该考虑升级到be6500 pro，512MB闪存，1G内存，全2.5G，加一个智能家居的中枢网关，一步到位。

**Comment by GitDjAr** [comment]
> 可以安装，我成功安装了，不过存储不太够，而且也不要对网速有太大的期望

你好可以指路下吗,

**Comment by moyuwuhen601** [comment]
> > 可以安装，我成功安装了，不过存储不太够，而且也不要对网速有太大的期望
> 
> 你好可以指路下吗,

[ShellCrash项目](https://github.com/juewuy/ShellCrash)

**Comment by Zippowxk** [comment]
体验下来 最终还是选择了软路由，省心，投入也不多, 科学上网 R2 R3足矣
