### ISSUE TITLE
WSL2 Ubuntu子系统执行等待

### ISSUE THREAD

**Issue by moyuwuhen601** [z-jack/BE5000_GetShell#2]
我的电脑是Windows11系统，起初下载了脚本后在windows中执行了，后来发现执行成功但是ssh连接失败，去到原博客发现有人反映此问题是字符编码的问题。索性打开了我的ubuntu子系统再次下载并执行，发现就卡在Start retriving SSH permission.了，重启路由器再次执行也是相同的问题。

**Comment by moyuwuhen601** [comment]
后来重置后又尝试了Ubuntu live，发现还是卡在Start retriving SSH permission

**Comment by z-jack** [comment]
因为我用的macOS，Windows的bug我还真不知道怎么解决，目前手头没这设备，之后有时间的时候看一下

**Comment by moyuwuhen601** [comment]
> 因为我用的macOS，Windows的bug我还真不知道怎么解决，目前手头没这设备，之后有时间的时候看一下

好吧，不过它在linux中出现Start retriving SSH permission，怎么可以看它具体哪报错了呢？

**Comment by z-jack** [comment]
> > 因为我用的macOS，Windows的bug我还真不知道怎么解决，目前手头没这设备，之后有时间的时候看一下
>
> 好吧，不过它在linux中出现Start retriving SSH permission，怎么可以看它具体哪报错了呢？

可以尝试在代码里加一些log（狗头），例如被注释的 crack.py 43行。
https://github.com/z-jack/BE5000_GetShell/blob/167183c6f850567ec8c7ecd1aebdb3ecce80a756/crack.py#L43

**Comment by moyuwuhen601** [comment]
> > > 因为我用的macOS，Windows的bug我还真不知道怎么解决，目前手头没这设备，之后有时间的时候看一下
> > 
> > 
> > 好吧，不过它在linux中出现Start retriving SSH permission，怎么可以看它具体哪报错了呢？
> 
> 可以尝试在代码里加一些log（狗头），例如被注释的 crack.py 43行。
> 
> https://github.com/z-jack/BE5000_GetShell/blob/167183c6f850567ec8c7ecd1aebdb3ecce80a756/crack.py#L43

嗯好，我试试，主要我也是小白，麻烦大佬了

**Comment by moyuwuhen601** [comment]
主动退出后，拿着报错的信息去问ChatGPT它说好像是请求阶段一直在等待响应，我也觉得linux系统下的问题是这个

**Comment by moyuwuhen601** [comment]
> > > 因为我用的macOS，Windows的bug我还真不知道怎么解决，目前手头没这设备，之后有时间的时候看一下
> > 
> > 
> > 好吧，不过它在linux中出现Start retriving SSH permission，怎么可以看它具体哪报错了呢？
> 
> 可以尝试在代码里加一些log（狗头），例如被注释的 crack.py 43行。
> 
> https://github.com/z-jack/BE5000_GetShell/blob/167183c6f850567ec8c7ecd1aebdb3ecce80a756/crack.py#L43

请问一下大佬，您知道这个字符编码问题具体是出现在哪里吗？我现在想修改都不知道修改哪个地方。抱歉我的问题有点小白了。

**Comment by moyuwuhen601** [comment]
对了，我发现它的token是会变化的，我每次登录路由器后台管理界面它的token都不一样

**Comment by thisThink** [comment]
解决了吗，搞了一下午，没搞定，卡在Start retriving SSH permission.不动；

**Comment by moyuwuhen601** [comment]
> 解决了吗，搞了一下午，没搞定，卡在Start retriving SSH permission.不动；

搞定了
