### ISSUE TITLE
修正 windows 下執行無法建立目錄

### ISSUE THREAD

**Issue by lschg** [z-jack/BE5000_GetShell#5]
發現在 windows 執行 crack.py 時，BE5000 會建立 /etc/config/dropbear? 目錄，造成程式執行失敗 ?
經修改程式碼後，在 windows 下原始的 ping1.template 可成功建立 /etc/config/dropbear
因只在 windows 下執行並不知其他作業系統狀況，提出敬請參考。
修改部分如下:
def create_payload():
    with open("ping1.template", "r") as file:
        template = file.read()
    # Replace Windows line endings with Unix line endings
    # template = template.replace('\r\n', '\n')
    txt = template.replace("{{LOCAL_IP}}", LOCAL_IP).replace("{{PORT}}", str(PORT))
    binary = txt.encode()
    with open("ping1", "wb") as file:
        # file.write(template.replace("{{LOCAL_IP}}", LOCAL_IP).replace("{{PORT}}", str(PORT)))
        file.write(binary)
![sshot-18](https://github.com/user-attachments/assets/f5f3f2fb-b448-4b94-9599-9ccdb74f3b73)

**Comment by z-jack** [comment]
感谢，因手头没有Windows设备，一直没办法测试。我会把你的解决方案作为Windows的执行代码
